# Generated by Django 3.1.7 on 2021-03-30 20:27

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to=api.models.patient_report_directory_path)),
                ('remark', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
